FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps ./apps
COPY packages ./packages

# INSTALL DEPENDENCIES
RUN npm install

# SCRIPT TO RUN THE PRISMA CLIENT GENERATE  
RUN npm run db:generate

# BUILD
RUN npm run build

CMD [ "npm","run","start-user-app" ]