name: Build & Deploy to DockerHub

on:
  push:
    branches:
      - master
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Log into DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME }}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build & Push Docker img
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./docker/Dockerfile.user
          push: true
          tags: siliconborn23/ci-cd_prac:latest

      - name: Verify Pushed img
        run: docker pull siliconborn23/ci-cd_prac:latest
